### ISSUE TITLE
JSON Question

### ISSUE THREAD

**Issue by beauhaus** [aspittel/ama#1]
HI~!
Really like yer site & like the design.

I'm dying to know... I've seen a lot of confusing info about this.

Self-referencing JSON
----------------------

I noticed that you might've used elephant SQL at one point(?).

Would you happen to know whether there might be a way to create a json file that containing objects that reference other objects?
("tables that reference other tables" (?) )

One might do this so as to "query" a json object much like a sql table.

I have no idea whether this is a ridiculous question...I simply thought of something that I'd really like to get a definitive answer on and thought I'd reach out. :)

Many thanks for the ama!

-B

**Comment by aspittel** [comment]
Thanks!
I use PostgreSQL a bunch, and love it!

For JSON databases, you could use MongoDB and use embedded documents to relate data, or you could use document references which would be more similar to SQL's foreign keys.

In order to do this with JavaScript, the easiest way would be just to nest the data to begin with, otherwise you would have to loop through the data structure in order to join it. [Lodash](https://lodash.com/) has a bunch of methods that would be helpful for "querying" JSON data!
