### ISSUE TITLE
Job search

### ISSUE THREAD

**Issue by dlousa92** [aspittel/ama#3]
Hey Ali, recent grad from GA DC here. What's your biggest piece of advice entering the job market, and dealing with imposter syndrome?

**Comment by aspittel** [comment]
Hey! Congrats on graduating, I miss teaching on campus there!

I have a [Twitter thread](https://twitter.com/ASpittel/status/950883968311848960) that I put together forever ago on my career advice. But, especially in DC, go to meetups. There are so many -- [DCTechCal](http://dctechcal.com/) has a ton of awesome ones listed. You'll meet a ton of people there who can be super helpful. Also, I think having an awesome portfolio is especially important for bootcamp grads -- I have a [post](https://zen-of-programming.com/kickass-portfolio) on creating them and I'm totally willing to look over anybody's site!

Dealing with imposter syndrome is a whole nother animal, and I definitely don't have a solution. I've been doing this for a few years, and I still definitely struggle with it. That being said, compare yourself to past you instead of anybody else -- think about how much you've grown as a developer and all that you know compared to 12 weeks ago. I also find it really helpful to keep track of my wins or nice feedback from people and go back over that on hard days. I organize it all on Google Keep -- whether it be nice comments from students, a link to a cool project I made, a quick note on something being easy now that used to be hard, or even just a compliment from a friend that meant a lot.

I really like both of these questions -- I may do longer form answers in the near future!

**Comment by dlousa92** [comment]
I'd love if you could take a look at my portfolio and let me know what you
think if you had the chance! I could use some feedback on well pretty much
everything. I read through your blog post and I'm working on getting a
custom url asap. A play on words with my name isn't so easy 😅. Thank you
so much for your advice!

Portfolio -- https://dlousa92.github.io/

**Comment by aspittel** [comment]
Oh for sure! You could just do your name for it!

I really like the styling of it -- Playfair is one of my favorite fonts. You could increase font size a little bit for the body content, and for the secondary headers in the top square. You also may want a link to contact you in that initial section so that people can access that fast, I would make it some bolder color too. Again, looks awesome!
