### ISSUE TITLE
What's the most rewarding thing about being an instructor?

### ISSUE THREAD

**Issue by michaellee** [aspittel/ama#6]
I'm a fan of your resources and work. Curious what you find the most rewarding as an instructor both online to your audience and in class?

**Comment by aspittel** [comment]
Thank you so much!

I love to see the growth in students in person -- it's so cool to see people on day one who have no idea how to code be employable web developers three or six months later. I love seeing the light bulbs go off when they learn something new. I also really enjoy cultivating a really healthy classroom culture -- that's one of the things I've worked really hard on, to make sure that people feel like its a safe and inclusive learning environment.

Online, its a little bit different since I don't completely see the growth in the same way that I do in person. People leaving comments that are really nice makes it so worth it though, and my articles are really targetted at myself when I was first learning how to code, which I think is cool!
